### ISSUE TITLE
Extended Circular Node not listed.

### ISSUE THREAD

**Issue by ghost** [Andrey2470T/circular_saw_ext#1]
Greetings,

There is a strange little Issue, when I tested your Mod, none of the extra blocks is shown, I only got the other half of the halfstair now listed in the circular saw, but none of the "circular_saw_ext" blocks.

Funny part is, the ability to scroll in the circular saw stays, when you disable "circular_saw_ext" until you replace it.

**Comment by Andrey2470T** [comment]
It is pretty strange. Probably you use the most actual version of moreblocks. Because my addon code is based off older one and all microblocks are shown in the circular saw inventory. I will check out today this thing.

And yes, you need to replace it again if you disable the addon or add/remove some shapes. That happens because of the formspec for the circular saw is set once when it is placed, not after restart.

**Comment by ghost** [comment]
Yes I use the most up to date version of moreblocks, downloaded through the Minetest Engine itself,
same for the circular_saw_ext Mod.

**Comment by Andrey2470T** [comment]
Fixed: 9b97572501b7e6215dc1bd60e4bd994a0da48b29
![Снимок экрана от 2024-04-02 12-14-58](https://github.com/Andrey2470T/circular_saw_ext/assets/25750346/a94084f1-3f5a-4b3b-b45d-be10a81de35e)
